DESIGN_NAME: user_project_example
VERILOG_FILES: dir::src/user_project_example.v

CLOCK_PORT: clk_i
CLOCK_PERIOD: 20
MAX_FANOUT_CONSTRAINT: 4
RUN_CTS: true

RT_MAX_LAYER: Metal4

PL_TARGET_DENSITY_PCT: 60

IO_PIN_ORDER_CFG: dir::pin_order.cfg
PDN_MULTILAYER: false
FP_SIZING: absolute
DIE_AREA: [0, 0, 600, 600]

RUN_MAGIC_DRC: true

VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
